USE master
GO
CREATE DATABASE QuanLyMuaBanLinhKien
GO
USE QuanLyMuaBanLinhKien
GO
CREATE TABLE LinhKien(
	MaLinhKien INT PRIMARY KEY IDENTITY,
	TenLinhKien NVARCHAR(50) NOT NULL,
	NgaySanXuat DATETIME NOT NULL,
	HangSanXuat NVARCHAR(50) NOT NULL,
	SoLuong INT CHECK(SoLuong > 0) DEFAULT 1,
	DonGia MONEY CHECK(DonGia > 0) DEFAULT 1000
)
GO
CREATE TABLE KhachHang(
	MaKhachHang INT PRIMARY KEY IDENTITY,
	TenKhachHang NVARCHAR(50),
	SoDienThoai NVARCHAR(10) NOT NULL,
	DiaChi NVARCHAR(100) NOT NULL,
)
CREATE TABLE NhanVien(
	MaNhanVien INT PRIMARY KEY IDENTITY,
	TenNhanVien NVARCHAR(50) NOT NULL,
	TenDangNhap NVARCHAR(50) NOT NULL,
	MatKhau NVARCHAR(50) NOT NULL,
	VaiTro BIT DEFAULT 1
)
GO
CREATE TABLE DonHang(
	MaDon INT PRIMARY KEY IDENTITY,
	MaKhachHang INT FOREIGN KEY REFERENCES KhachHang(MaKhachHang),
	NgayMua DATETIME NOT NULL DEFAULT GETDATE(),
	MaNhanVien INT FOREIGN KEY REFERENCES NhanVien(MaNhanVien),
	GiamGia INT DEFAULT 0,
	ThanhTien MONEY CHECK(ThanhTien > 0) DEFAULT 1000,
)
GO
CREATE TABLE ChiTietDonHang(
	MaChiTietDon INT PRIMARY KEY IDENTITY,
	MaDon INT FOREIGN KEY REFERENCES DonHang(MaDon),
	MaLinhKien INT FOREIGN KEY REFERENCES LinhKien(MaLinhKien),
	SoLuong INT CHECK(SoLuong > 0) DEFAULT 1,
	DonGia MONEY CHECK(DonGia > 0) DEFAULT 1000,
)
GO
INSERT INTO NhanVien
VALUES 
	('admin','admin','1',0),
	('nv','nv','1',1)