USE master
GO
CREATE DATABASE QuanLyMuaBanLinhKien
GO
USE QuanLyMuaBanLinhKien
GO
CREATE TABLE LinhKien(
	MaLinhKien INT PRIMARY KEY,
	TenLinhKien NVARCHAR(50) NOT NULL,
	NgaySanXuat DATETIME NOT NULL,
	TinhTrang NVARCHAR(50) NOT NULL,
	SoLuong INT CHECK(SoLuong > 0) DEFAULT 1,
	DonGia MONEY CHECK(DonGia > 0) DEFAULT 1000,
	NhaSanXuat NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE KhachHang(
	MaKhachHang INT PRIMARY KEY,
	TenKhachHang NVARCHAR(50),
	SoDienThoai NVARCHAR(10) NOT NULL,
	DiaChi NVARCHAR(100) NOT NULL,
)
CREATE TABLE NhanVien(
	MaNhanVien INT PRIMARY KEY,
	TenNhanVien NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE DonHang(
	MaDon INT PRIMARY KEY,
	MaKhachHang INT FOREIGN KEY REFERENCES KhachHang(MaKhachHang),
	NgayMua DATETIME NOT NULL DEFAULT GETDATE(),
	MaNhanVien INT FOREIGN KEY REFERENCES NhanVien(MaNhanVien),
	TongTien MONEY CHECK(TongTien > 0) DEFAULT 1000,
)
GO
CREATE TABLE ChiTietDonHang(
	MaChiTietDon INT PRIMARY KEY,
	MaDon INT FOREIGN KEY REFERENCES DonHang(MaDon),
	MaLinhKien INT FOREIGN KEY REFERENCES LinhKien(MaLinhKien),
	SoLuong INT CHECK(SoLuong > 0) DEFAULT 1,
	DonGia MONEY CHECK(DonGia > 0) DEFAULT 1000,
	TongTien AS ISNULL(SoLuong * DonGia, 0)
)
GO